### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by leewenhua** [moshang-xc/lottery#13]
您好，项目很nice，请问这个怎么部署到服务器上呢？

**Comment by CN-Ocean** [comment]
同问, 还有一个问题 如何手动暂停抽奖  现在抽奖时间太短 气氛调情不起来

**Comment by moshang-xc** [comment]
> 您好，项目很nice，请问这个怎么部署到服务器上呢？

设计的时候npm run serve就可以把服务跑起来了，不需要部署到服务器呀

**Comment by moshang-xc** [comment]
> 同问, 还有一个问题 如何手动暂停抽奖 现在抽奖时间太短 气氛调情不起来

目前没有这个功能

**Comment by CN-Ocean** [comment]
> > 同问，还有一个问题如何手动暂停抽奖现在抽奖时间太短气氛调情不起来
> 
> 目前没有这个功能

我尝试过修改添加一个暂停按钮 但是随之出现的问题很多

**Comment by GAtomis** [comment]
> > > 同问，还有一个问题如何手动暂停抽奖现在抽奖时间太短气氛调情不起来
> > 
> > 
> > 目前没有这个功能
> 
> 我尝试过修改添加一个暂停按钮 但是随之出现的问题很多

通过修改转动时间和转动圈数来延长球体在抽奖都周期
