### ISSUE TITLE
安装进程卡在\product npm install

### ISSUE THREAD

**Issue by fzupang** [moshang-xc/lottery#14]
![image](https://user-images.githubusercontent.com/26203964/103740512-50da4200-5032-11eb-9d6b-3dc57c3b49c9.png)
安装进程卡在
F:\>cd lottery-master

F:\lottery-master>cd server

F:\lottery-master\server>npm install
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'F:\lottery-master\server\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 193 packages from 139 contributors and audited 264 packages in 35.104s
found 101 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

F:\lottery-master\server>cd ../product
**_F:\lottery-master\product>npm install
[            ......] / extract:@webassemblyjs/helper-wasm-bytecode: sill extract @webassemblyjs/helper-wasm-bytecode@1._** 
无法完成安装

**Comment by Sys-Myl** [comment]
删除node_modules，删除package-lock.json，重新install即可。
