### ISSUE TITLE
特别奖概率问题及少量抽奖人员抽取完毕后系统异常

### ISSUE THREAD

**Issue by Sys-Myl** [moshang-xc/lottery#15]
1、当所有奖项都抽取完毕后，临时抽取的特别奖经测试发现是从所有奖项获得者之外抽取的，并不是所有人概率都相同；
2、特别奖将所有人都抽取完毕后，`Uncaught TypeError: Cannot read property '1' of undefined``Uncaught (in promise) TypeError: Cannot read property '1' of undefined`，所有按钮失效，isLotting 持久 false。

**Comment by moshang-xc** [comment]
已修复抽奖人员不足抱错问题，但如果初始抽奖人员总人数就少于每次抽取的人员个数，属于数据本身不合理，不考虑这种情况，系统无法运行。
