### ISSUE TITLE
奖项配置能否做成页面配置

### ISSUE THREAD

**Issue by Nemo1986** [moshang-xc/lottery#18]
页面配置完能立即执行。
现在是在config里面配置，还得登服务器，修改完还得重启服务有些繁琐。

**Comment by GAtomis** [comment]
我基于楼主做了个纯web版本,可以配置mock

**Comment by GAtomis** [comment]
> 页面配置完能立即执行。 现在是在config里面配置，还得登服务器，修改完还得重启服务有些繁琐。

https://github.com/GAtomis/lottery-web 基于大佬开发的lottery前端版本

**Comment by moshang-xc** [comment]
可以先参考小姐姐的方案，后续考虑添加
