### ISSUE TITLE
人员导入能否直接从页面导入

### ISSUE THREAD

**Issue by Nemo1986** [moshang-xc/lottery#19]
当前版本需登录服务器，再覆盖excel，有点麻烦呢。

**Comment by GAtomis** [comment]
还没测试好,测试玩我可以发到github上修改了些bug,不知道作者是否能同意。我可以捐献

**Comment by GAtomis** [comment]
https://github.com/GAtomis/lottery-web 基于大佬开发的lottery前端版本

**Comment by GAtomis** [comment]
> 当前版本需登录服务器，再覆盖excel，有点麻烦呢。

https://github.com/GAtomis/lottery-web 基于大佬开发的lottery前端版本

**Comment by moshang-xc** [comment]
可以试试小姐姐的方案

**Comment by Nemo1986** [comment]
> > 当前版本需登录服务器，再覆盖excel，有点麻烦呢。
> 
> https://github.com/GAtomis/lottery-web 基于大佬开发的lottery前端版本

好的哇
