### ISSUE TITLE
当抽奖人数少于奖品总数的时候，出现错误

### ISSUE THREAD

**Issue by Chickenbrother** [moshang-xc/lottery#20]
index.js?2321:492 Uncaught (in promise) TypeError: Cannot read property '1' of undefined
    at eval (index.js?2321:492)
    at Array.map (<anonymous>)
    at selectCard (index.js?2321:492)
    at eval (index.js?2321:628)

**Comment by Chickenbrother** [comment]
if (leftCount === 0) {
          addQipao("人员已抽完，现在重新设置所有人员可以进行二次抽奖！");
          basicData.leftUsers = basicData.users;
          leftCount = basicData.leftUsers.length;
        }
这段代码里，basicData.leftUsers=basicData.users  这句话，是否需要用深拷贝？

**Comment by moshang-xc** [comment]
已修复
