### ISSUE TITLE
这个项目很棒，想要打包成.exe的桌面应用，方便拷贝使用，有没有什么好的方案推荐？

### ISSUE THREAD

**Issue by jimmyka** [moshang-xc/lottery#21]

**Comment by moshang-xc** [comment]
目前我自己的做法是把整个项目（带上node.exe文件）打包，然后可以实现拷贝使用，没有去研究其他的方案。
目录结构是这样的，双击运行 【双击启动程序start.bat 】文件即可：
![1642669938(1)](https://user-images.githubusercontent.com/29499430/150308610-15a1f3d5-3fe4-4213-b975-abf70f8ddd21.jpg)

**Comment by wyf162** [comment]
hello，moshang，双击启动程序的脚本可以放一下吗。

**Comment by wyf162** [comment]
windows下实操后，小白入门总结，把dist目录拷贝出来。node，npm版本记得保持一致，最好是和dockerfile一致。(我是node20，解决了ssl问题就可以啦)。
.bat文件可以参考这句话
node ./server/index.js 18888
pause
还有就是调试过程中遇到的端口占用。
netstat -ano | findstr 18888
taskkill /pid {{pid}} -F
总结，非常好用。
