### ISSUE TITLE
能否设置抽完特等奖后就不再抽取，且每开始新奖品前都弹窗确认，抽完奖品后也加上弹窗确认

### ISSUE THREAD

**Issue by lilywang711** [moshang-xc/lottery#22]
本来想自己 review 代码去实现的，，，但是看完代码后觉得不太好加，每次点完按钮后没有及时的去保存 basicData.luckyUsers[type]，而是在下次抽奖之前去 saveData..

**Comment by moshang-xc** [comment]
因为还会有重新抽取的情况，所以每次点完按钮就没去保存了
