### ISSUE TITLE
product目录npm install失败

### ISSUE THREAD

**Issue by lihefengbj** [moshang-xc/lottery#23]
开始以为node版本问题，从v16.13.0切换到v12.18.2，还是报错：
![image](https://user-images.githubusercontent.com/26763374/148906085-0edf47b4-20f5-4b52-b997-741e9a5cbdb3.png)

**Comment by lihefengbj** [comment]
降到版本v10.16.2，后升级node-sass版本以满足node版本

**Comment by qiushui95** [comment]
@lihefengbj 兄弟  能不能把最后的package.json发一下，我跑不起来。谢谢

**Comment by lihefengbj** [comment]
{
    "name": "http-mini",
    "version": "1.0.4",
    "description": "a simple static web server base on Express",
    "main": "index.js",
    "bin": {
        "http-mini": "index.js"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "moshang",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/moshang-xc/web-server.git"
    },
    "homepage": "https://github.com/moshang-xc/web-server#readme",
    "license": "ISC",
    "dependencies": {
        "body-parser": "^1.18.2",
        "chokidar": "^2.0.3",
        "express": "^4.16.3",
        "node-xlsx": "^0.12.1",
        "opn": "^5.3.0"
    }
}

**Comment by lihefengbj** [comment]
@qiushui95 

{
    "name": "http-mini",
    "version": "1.0.4",
    "description": "a simple static web server base on Express",
    "main": "index.js",
    "bin": {
        "http-mini": "index.js"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "moshang",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/moshang-xc/web-server.git"
    },
    "homepage": "https://github.com/moshang-xc/web-server#readme",
    "license": "ISC",
    "dependencies": {
        "body-parser": "^1.18.2",
        "chokidar": "^2.0.3",
        "express": "^4.16.3",
        "node-xlsx": "^0.12.1",
        "opn": "^5.3.0"
    }
}

**Comment by lihefengbj** [comment]
@qiushui95 

{
    "name": "http-mini",
    "version": "1.0.4",
    "description": "a simple static web server base on Express",
    "main": "index.js",
    "bin": {
        "http-mini": "index.js"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "moshang",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/moshang-xc/web-server.git"
    },
    "homepage": "https://github.com/moshang-xc/web-server#readme",
    "license": "ISC",
    "dependencies": {
        "body-parser": "^1.18.2",
        "chokidar": "^2.0.3",
        "express": "^4.16.3",
        "node-xlsx": "^0.12.1",
        "opn": "^5.3.0"
    }
}

**Comment by qiushui95** [comment]
@lihefengbj 谢谢兄弟。虽然你发的是server里面的。我把nodejs换成 V9.11.2  解决了

**Comment by lihefengbj** [comment]
@qiushui95 不好意思发的时候没注意
