### ISSUE TITLE
部署运行问题

### ISSUE THREAD

**Issue by larval-zz** [moshang-xc/lottery#27]
您好，非常喜欢您的这个抽奖程序，只是在按照安装部署手册进行的时候，在server目录下面运行npm run serve时候报错，是不是我哪里的操作不正确呢，麻烦请您指教。
![npm error](https://user-images.githubusercontent.com/542242/150459279-e92cad53-8168-4584-90d5-a41a8e914897.jpg)

**Comment by larval-zz** [comment]
再追问一个问题，如何延长抽奖的时间呢，每次抽奖时间有些短了。

**Comment by moshang-xc** [comment]
npm run reserve是在product文件夹下运行，可以查看package.json中配置的指令进行排查。
抽奖时间暂时不支持延长。
