### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by eekon** [moshang-xc/lottery#28]
`[root@localhost product]# npm run serve

> lucky@1.0.0 serve
> npm run start

> lucky@1.0.0 start
> cd dist && node ../../server/index.js 8888

加载EXCEL数据文件
lottery server listenig at http://:::8888
/root/lottery/server/node_modules/opn/index.js:85
					reject(new Error('Exited with code ' + code));
					       ^

Error: Exited with code 3
    at ChildProcess.<anonymous> (/root/lottery/server/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
`

**Comment by yiliangjianghu** [comment]
我也遇到了这个错误， 作者可能是部署在windows下，opn是一个自动打开浏览器的工具，部署在linux下需要把这个工具注释掉就可以了
操作：
将/root/lottery/server/server.js    中第 270行的  【   openBrowser && opn(`http://127.0.0.1:${port}`); 】代码删除

**Comment by niubbhh** [comment]
跑npm run serve 显示
lucky@1.0.0 start
cd dist && node ../../server/index.js 8888
未找到指定路径是什么情况

**Comment by liuenshuo9510** [comment]
> 跑npm run serve 显示 lucky@1.0.0 start cd dist && node ../../server/index.js 8888 未找到指定路径是什么情况

我也遇到了这个错误，你解决了吗？

**Comment by liuenshuo9510** [comment]
> > 跑npm run serve 显示 lucky@1.0.0 start cd dist && node ../../server/index.js 8888 未找到指定路径是什么情况
> 
> 我也遇到了这个错误，你解决了吗？

我解决了，不要用 NPM 最新版，我用的 node v16.8

**Comment by qiyongzhanghao** [comment]
> 我也遇到了这个错误， 作者可能是部署在windows下，opn是一个自动打开浏览器的工具，部署在linux下需要把这个工具注释掉就可以了 操作： 将/root/lottery/server/server.js 中第 270行的 【 openBrowser && opn(`http://127.0.0.1:${port}`); 】代码删除

谢谢你，好人！
