### ISSUE TITLE
如何取消特别奖？

### ISSUE THREAD

**Issue by yxhokay** [moshang-xc/lottery#33]
请问下特别奖是否可以取消呢 或者直接改为一等奖？测试了一下好像直接删除type 0 无效，或者特别奖是否可以改为有限

**Comment by moshang-xc** [comment]
直接把server/config.js里面prizes数组特等奖相关的配置删除就行

**Comment by semi-xi** [comment]
注释了会无法使用的，奖品那边都少了一个
