### ISSUE TITLE
打包不能使用

### ISSUE THREAD

**Issue by QS-cmd-exe** [moshang-xc/lottery#37]
请问一下，这个打包是在product中打包吗，打包出来的文件不呢正常访问

**Comment by moshang-xc** [comment]
# 打包
npm run build

# 运行
npm run serve

# 开发调试
npm run dev

以上三个操作都在product文件夹内进行

**Comment by qcjxberin** [comment]
这种打包的话，后端8888的也是要专门运行吧？
