### ISSUE TITLE
主页如何改为2024

### ISSUE THREAD

**Issue by Fstrovsky** [moshang-xc/lottery#51]

**Comment by qiruizheng** [comment]
同问 @moshang-xc

**Comment by moshang-xc** [comment]
到了24年就会变成24，或者把电脑的时间修改为2024

**Comment by wyf162** [comment]
这个真的厉害

**Comment by 991547436** [comment]
function createHighlight() {
  let year = new Date().getFullYear() + "";
  year = "2025";
