### ISSUE TITLE
抽奖建议

### ISSUE THREAD

**Issue by GitHubBean** [moshang-xc/lottery#7]
1.进入抽奖，配置年份，现在默认获取当前的日期年：2019 高亮
2.抽奖后的本次开奖人员自适应显示；如果设置成：10人，还是当行一排显示，超过人员显示被遮住了

项目很nice ：-)

**Comment by moshang-xc** [comment]
OK，有时间再优化下

**Comment by moshang-xc** [comment]
已添加，10人及以下的排版适配
