### ISSUE TITLE
每次抽取人数bug

### ISSUE THREAD

**Issue by MakenChan** [moshang-xc/lottery#9]
![image](https://user-images.githubusercontent.com/20518466/95834167-37956280-0d6f-11eb-920b-05da224fa8f0.png)
比如下图圈起来的地方
![image](https://user-images.githubusercontent.com/20518466/95834247-509e1380-0d6f-11eb-927a-a98b8f3b6c60.png)
我第一次抽9个，第二次应该是抽剩下的部分，只剩下一个奖品，否则就会产生负数

**Comment by moshang-xc** [comment]
感谢，抽空解一下这个bug

**Comment by sunshinekl** [comment]
您好，初始化页面2020是写死的吗

**Comment by moshang-xc** [comment]
> 您好，初始化页面2020是写死的吗

自动获取的，根据电脑时间变化

**Comment by lzpswat** [comment]
> 感谢，抽空解一下这个bug

这个bug解决了吗?

**Comment by moshang-xc** [comment]
已修复
